"""Constant definitions."""
DOMAIN = "automatic_solar_panel_hvac"
SENSOR_KEY = "sensor"
SWITCH_KEY = "switch"
CONFIG = "config"
CONF_CLIMATE = "climate"
CONF_FRONIUS = "fronius_url"
CONF_LOW_CONSUMPTION = "low_consumption"
CONF_HIGH_CONSUMPTION = "high_comsumption"
CONF_TURN_ON_THRESHOLD = "turn_on_threshold"
CONF_TURN_OFF_THRESHOLD = "turn_off_threshold"
